### ISSUE TITLE
biliocr.py不能在python3下运行

### ISSUE THREAD

**Issue by bieberg0n** [fuckbilibili/Bilibili-Silver-Grab#6]
建议把biliocr.py中78-85行的print语句改成print()函数以兼容python3
还有xrange()改为range()

**Comment by Seraphli** [comment]
还有全改成英文,中文居然是不用GBK的..简直蛋疼...

**Comment by bieberg0n** [comment]
@Seraphli 说明在http://www.fuckbilibili.com/bililivesilver.html

**Comment by hanbang-wang** [comment]
fixed by @chinuno-usami
